import Head from "next/head";
import BottomBanner from "../components/BottomBanner";
import MainBanner from "../components/MainBanner";
import Menu from "../components/Menu";
import NewsLine from "../components/NewsLine";
import OurProducts from "../components/OurProducts";
import SignUpBanner from "../components/SignUpBanner";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Menu />
        <NewsLine />
        <MainBanner />
        <OurProducts />
        <BottomBanner />
        <SignUpBanner />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
